language: generic

services:
 - docker

stages:
  - build
  - test_client
  - test_api

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
  - sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
  - sudo chmod +x /usr/bin/docker-compose

jobs:
  include:
    - stage: build
      script: docker-compose up --build -d

    - stage: test_client
      script: docker-compose run --rm client yarn run test:unit # test client
    
    - stage: test_api
      script: docker-compose run --rm api bundle exec rails test # test api
