version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /usr/src/client/node_modules

# rebuild image and start
# sudo docker-compose up --build -d

# test client
# sudo docker-compose run --rm client yarn run test:unit